name:                blueberry-monad
version:             0.1.0.1
github:              "abjoru/blueberry-monad"
license:             BSD3
author:              "Andreas Bjoru"
maintainer:          "andreas@bjoru.com"
copyright:           "2020 Andreas Bjoru"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/blueberry-monad#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: 
    - lib
    - plugins
    - BMonad
  dependencies:
    - directory
    - filepath
    - xmobar
    - X11
    - xmonad
    - xmonad-contrib
    - containers
    - unix
    - ini
    - regex-posix
    - text
    - time
    - aeson
    - http-conduit
    - unordered-containers

executables:
  blueberry-monad:
    main:                Bmonad.hs
    source-dirs:         wm
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
    dependencies:
      - blueberry-monad
      - xmonad
      - xmonad-contrib
      - directory
      - filepath
      - X11

  blueberry-mobar:
    main:                Bmobar.hs
    source-dirs:         bar
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - blueberry-monad
      - xmobar

tests:
  test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - blueberry-monad
      - hspec >=2.0.0
    ghc-options:
      - -Wall
      - -threaded
      - -rtsopts
      - '"-with-rtspots=-N -qg"'
